apiVersion: v1
kind: DeploymentConfig
metadata:
  name: busy-dc
  labels:
    app: busy
spec:
  replicas: 2
  matchLabels:
    app: busy
  template:
    metadata:
      labels:
        app: busy
    spec:
      containers:
      - name: busybox
        image: busybox
        command:
          - sleep
          - "3600"
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
