apiVersion: v1
kind: DeploymentConfig
metadata:
  name: kubia-dc
  labels:
    app: kubia
spec:
  replicas: 2
  matchLabels:
    app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: kubia
        image: dmoessne/kubia:7.0
